# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "MATH 263: Numerical differential equations"
author: Ethan Smith
#logo: gcc_seal.png

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

sphinx:
  extra_extensions:
    - sphinx_proof # enables prf:theorem and prf:proof directives
    #- sphinxcontrib.tikz # supposed to enable tikz directive

execute:
  execute_notebooks: cache # cache notebook results to save time rebuilding
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: nde263.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
#
## Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true
