name: math263-notes
channels:
  - conda-forge
  - defaults
dependencies:
  - ghp-import
  - jupyter-book<2.0
  - jupyterlab-myst
  - jupytext
  - matplotlib
  - notebook
  - numpy
  - sympy
  - tabulate
  - scipy
  - pytest
  - ffmpeg
  - sphinx-proof
