name: 'test'
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - sympy
  - jupytext
  - tabulate
  - notebook
  - jupyterlab-myst
  - jupyter-book
  - pip
  - pip:
      - sphinx-proof
#prefix: /opt/anaconda3/envs/math263
